# Generated by Django 4.2.2 on 2023-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Description', models.CharField(max_length=5000)),
                ('Name', models.CharField(max_length=64)),
                ('Basket', models.ManyToManyField(blank=True, related_name='Items', to='Shop.basket')),
            ],
        ),
    ]
