# Generated by Django 4.2.2 on 2023-06-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='Name',
            field=models.CharField(default='Basket', max_length=64),
        ),
    ]
